### PR TITLE
Do not compare + segments unless wildcards in either accept or priority

### LINKED ISSUE #93: Regression in recent releases
Copy/paste from #92:

Hi @willdurand, @weierophinney! This PR and the new release (2.3) breaks our test suite on api-platform/core. See https://travis-ci.org/api-platform/core/jobs/228775063 for example.

I have this accept header: application/hal+json.
My priorities are:

[0] => "application/ld+json"
[1] => "application/hal+json"
[2] => "application/xml"
[3] => "text/xml"
[4] => "application/json"
[5] => "text/html"
Then, the AbstractNegotiator::getBest() method now returns application/ld+json instead of application/hal+json before.

It looks like something is not working properly here, nop? Thanks.

(Ping @dunglas)

### PR DESCRIPTION
**Pull request by weierophinney**
Fixes #93. If there are no wildcard segments in either the subtype or `+` segment of either the Accept header or priority, do not attempt to compare them.

Adds more tests for #92 as well, using `*` subtypes in both the Accept header and priorities, to validate that different combinations work as expected.

### CODE REVIEW

**Comment by weierophinney** [comment]
@willdurand , @meyerbaptiste — ready to review!

**Comment by weierophinney** [comment]
And @dunglas !

**Comment by dunglas** [comment]
Our test suite is green with this patch (see https://github.com/api-platform/core/pull/1104), thanks @weierophinney!

File: src/Negotiation/Negotiator.php [hunk 1]
```diff
@@ -49,11 +49,17 @@ protected function match(AcceptHeader $accept, AcceptHeader $priority, $index)
         list($acceptSub, $acceptPlus) = $this->splitSubPart($acceptSub);
         list($prioritySub, $priorityPlus) = $this->splitSubPart($prioritySub);
 
+        // If no wildcards in either the subtype or + segment, do nothing.
+        if (! ($acceptBase === '*' || $baseEqual)
+            || ! ($acceptSub === '*' || $prioritySub === '*' || $acceptPlus === '*' || $priorityPlus === '*')) {
```
Comment (sstok) [inline src/Negotiation/Negotiator.php]: According to PSR-2 when the if is multi-line the `) {` needs to be on it's own line.

Comment (weierophinney) [inline src/Negotiation/Negotiator.php]: Surprised my linter didn't catch that! Fixing now and pushing momentarily. Also, for internal consistency, removing spaces following `!` operators.

**Comment by dunglas** [comment]
@willdurand do you think you'll soon have time soon to merge this patch and create a new release? It's currently breaking all API Platform projects when running `composer update` but we can prevent this by tagging a release on our side preventing to install 2.3+.

**Comment by willdurand** [comment]
> @willdurand do you think you'll soon have time soon to merge this patch and create a new release? It's currently breaking all API Platform projects when running composer update but we can prevent this by tagging a release on our side preventing to install 2.3+.

doing this right now, was on holidays earlier this week..

**Comment by willdurand** [comment]
@dunglas just released [2.3.1](https://github.com/willdurand/Negotiation/releases/tag/v2.3.1)

**Comment by willdurand** [comment]
Thanks everyone! ❤️
